# SYNOPSIS:
#
#   make all    - makes everything
#   make main   - makes the main executable..
#   make test   - makes tests.
#   make clean  - removes all files generated by make.

# TODO:
#   - Search for more elegant way to compile everything into TEST_DIR
#   instead of abusing addprefix and TEST_DIR Maybe consider recursive
#   Makefiles, even if they are considered "harmful"?

# Flags passed to the C++ compiler: common, include and linking flags.
CXXFLAGS += -std=c++14 -g -Wall -Wextra -pthread -O0
LFLAGS += -lsfml-system -lsfml-window -lsfml-graphics
IFLAGS += -I.


# All the .o from the .cpp files of the main project to compile.
OBJECTS = main.o LSystem.o Turtle.o

# Main executable
TARGET = procgen.out


# Path the root of googletest
GTEST_DIR = /usr/src/googletest/googletest

# Flags passed to the preprocessor
GTEST_CPPFLAGS = -isystem $(GTEST_DIR)/include

# All Google Test headers.
GTEST_HEADERS = $(GTEST_DIR)/include/gtest/*.h \
                $(GTEST_DIR)/include/gtest/internal/*.h

# Internal googletest variable.
GTEST_SRCS_ = $(GTEST_DIR)/src/*.cc $(GTEST_DIR)/src/*.h $(GTEST_HEADERS)


# Where to find the tests.
TEST_DIR = test

# All tests for this project.
TESTS = LSystemTest.test


all : main test

clean :
	rm -f *.o *.a *.out \
	$(TEST_DIR)/*.o $(TEST_DIR)/*.a $(TEST_DIR)/*.test


# main: Links all the .o file from OBJECTS into TARGET
main : $(OBJECTS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) *.o $(LFLAGS)

# test: Asks to generates all OBJECTS and TESTS files
test: $(OBJECTS) $(TESTS)


# Each .o file is compiled with its associated *.cpp file.
# Note: '%.cpp' is necessary: an implicit rule breaks this Makefile if
# it is not present.
%.o : %.cpp
	$(CXX) $(CXXFLAGS) -c $^ $(IFLAGS)


# Compiles and archives googletest internals.
#   - gtest-main is used when test files are presented without the
#   main() function
gtest-all.o : $(GTEST_SRCS_)
	$(CXX) $(GTEST_CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest-all.cc -o $(TEST_DIR)/$@

gtest_main.o : $(GTEST_SRCS_)
	$(CXX) $(GTEST_CPPFLAGS) -I$(GTEST_DIR) $(CXXFLAGS) -c \
            $(GTEST_DIR)/src/gtest_main.cc -o $(TEST_DIR)/$@

gtest.a : gtest-all.o
	$(AR) $(ARFLAGS)  $(addprefix $(TEST_DIR)/, $@ $^)

gtest_main.a : gtest-all.o gtest_main.o
	$(AR) $(ARFLAGS) $(addprefix $(TEST_DIR)/, $@ $^)

# Compiles every *Test.cpp.
%Test.o :
	$(CXX) $(GTEST_CPPFLAGS) $(CXXFLAGS) -c $(TEST_DIR)/$*Test.cpp -o $(TEST_DIR)/$@ $(IFLAGS)

# Links each *Test.o with googletest internals to an executable per test.
%Test.test : %Test.o gtest_main.a
	$(CXX) $(GTEST_CPPFLAGS) $(CXXFLAGS) -o $(addprefix $(TEST_DIR)/, $@ $^) $*.o $(IFLAGS) -lpthread

